apiVersion: v1
kind: Service
metadata:
  name: mini-ethos-service
spec:
  type: NodePort       # Exposes the service on a port on each node
  selector:
    app: mini-ethos    # Sends traffic to pods with label 'app: mini-ethos'
  ports:
    - protocol: TCP
      port: 80         # The port the Service listens on
      targetPort: 8000 # The port your Container is listening on